---
env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
rules:
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  no-await-in-loop: error
  no-console: [error, allow: [warn, error]]
  no-unreachable-loop: error
  no-unsafe-optional-chaining: error
  no-useless-backreference: error
  class-methods-use-this: error
  default-case-last: error
  default-param-last: error
  curly: error
  eqeqeq: error
  dot-notation: error
  no-empty-function: error
  no-return-assign: [error, always]
  no-self-compare: error
  no-unused-expressions: [error, enforceForJSX: true]
  no-useless-return: error
  radix: error
  no-shadow: error
  no-undefined: error
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  lines-between-class-members: error
  max-len: [error, 120]
  new-cap: error
  no-lonely-if: error
  no-negated-condition: error
  no-unneeded-ternary: error
  prefer-object-spread: error
  arrow-body-style: [error, as-needed]
  no-confusing-arrow: [error, allowParens: true]
  no-duplicate-imports: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-const: error
  prefer-rest-params: error
  sort-imports: error
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': warn
  'react/no-access-state-in-setstate': error
  'react/no-array-index-key': error
  'react/no-danger': error
  'react/no-did-mount-set-state': error
  'react/no-did-update-set-state': error
  'react/no-redundant-should-component-update': error
  'react/no-this-in-sfc': error
  'react/no-typos': error
  'react/no-unsafe': error
  'react/no-unused-prop-types': error
  'react/no-unused-state': error
  'react/no-will-update-set-state': error
  'react/prefer-es6-class': error
  'react/prefer-stateless-function': error
  'react/self-closing-comp': error
  'react/sort-comp': error
  'react/static-property-placement': error
  'react/style-prop-object': error
  'react/void-dom-elements-no-children': error
  'react/jsx-boolean-value': error
  'react/jsx-fragments': error
  'react/jsx-no-useless-fragment': error
